#!/usr/bin/env python3

import json
from pprint import pprint
import colors as c

with open('Turtle.json') as f:
    data = json.load(f)
f.close

#print data
#pprint data

print(c.magenta + """
    name:        {name}
    speed:       {speed}
    Defense:     {defense}
    Description: {description}
    Evolutions:  {evolutions[0]}
""".format(**data))
