#!/usr/bin/env python3

import json, requests
from pprint import pprint
import sys

try:
    r =  requests.get(url='http://pokeapi.co/api/v1/pokemon/' + sys.argv[1])
    data = json.loads(r.text)
except IndexError
    print("usage: fooget <pokemon>")
    exit(-1)

#pprint(data)
print("Name: " + data["name"])
print("Speed: " + str(data["speed"]))
print("Defense: " + str(data["defense"]))

for move in data["moves"]:
    print(move["name"], end=", ")
